#!/usr/bin/env bash

set -euo pipefail

# Create project directories
mkdir -p pages src models data/raw data/processed notebooks utils

# Create main Streamlit app
cat > app.py <<'EOF'
import streamlit as st

st.title('Toronto Collision Predictor')

st.sidebar.title('Navigation')

st.write('Welcome to the Toronto Collision Predictor app!')
EOF

# Create page files
cat > pages/1_Home.py <<'EOF'
import streamlit as st

st.title('Home')
st.write('Overview and introduction.')
EOF

cat > pages/2_Exploratory_Analysis.py <<'EOF'
import streamlit as st

st.title('Exploratory Analysis')
st.write('Exploratory data analysis and visualizations.')
EOF

cat > pages/3_Data_Cleaning.py <<'EOF'
import streamlit as st

st.title('Data Cleaning')
st.write('Data cleaning and preprocessing steps.')
EOF

cat > pages/4_Modeling.py <<'EOF'
import streamlit as st

st.title('Modeling')
st.write('Model training, evaluation, and selection.')
EOF

cat > pages/5_Prediction.py <<'EOF'
import streamlit as st

st.title('Prediction')
st.write('Make predictions using the trained model.')
EOF

# Create src module files
cat > src/__init__.py <<'EOF'
# Core Python modules for the project
EOF

cat > src/data_loader.py <<'EOF'
import pandas as pd


def load_raw_data(path):
    return pd.read_csv(path)
EOF

cat > src/preprocessing.py <<'EOF'

def clean_data(df):
    return df
EOF

cat > src/feature_engineering.py <<'EOF'

def create_features(df):
    return df
EOF

cat > src/visualizations.py <<'EOF'

def plot_data(df):
    pass
EOF

cat > src/models.py <<'EOF'

def train_model(X, y):
    pass


def load_model(path):
    pass
EOF

cat > src/utils.py <<'EOF'

def log(message):
    print(message)
EOF

# Create placeholder files
cat > models/.gitkeep <<'EOF'
# Keep models directory in git
EOF

cat > data/raw/.gitkeep <<'EOF'
# Keep raw data directory in git
EOF

cat > data/processed/.gitkeep <<'EOF'
# Keep processed data directory in git
EOF

cat > notebooks/.gitkeep <<'EOF'
# Keep notebooks directory in git
EOF

cat > utils/.gitkeep <<'EOF'
# Keep utils directory in git
EOF

# Create other files
cat > requirements.txt <<'EOF'
streamlit
pandas
numpy
scikit-learn
xgboost
EOF

cat > README.md <<'EOF'
# Toronto Collision Predictor

Project scaffold generated by create_project.sh.
EOF

cat > .gitignore <<'EOF'
__pycache__/
*.pyc
*.pkl
.env
.DS_Store
logs/

# Data files
data/raw/*
data/processed/*
EOF

cat > streamlit_config.toml <<'EOF'
[server]
headless = true
port = 8501
enableCORS = false
EOF

echo "Project skeleton created successfully."
